server:
  port: 8081
spring:
  cloud:
    stream:
      bindings:
        order-out-0:
          destination: order
        approvedOrder-in-0:
          destination: approved
        rejectedOrder-in-0:
          destination: rejected
      function:
        definition: approvedOrder;rejectedOrder